### ISSUE TITLE
Using with React Native

### ISSUE THREAD

**Issue by mikev10** [AJFunk/cannabis-reports#4]
Hi,

Do you have any examples of how to use with React Native?

I tried doing this:
```
import React, { Component } from 'react';
import { ActivityIndicator } from 'react-native';
import {
  View,
  ListView,
  Text,
  Image,
  Tile,
  Title,
  Subtitle,
  Overlay,
  Screen
} from '@shoutem/ui';
import { Strain } from 'cannabis-reports';
import { setCannabisReportsKey } from 'cannabis-reports';
setCannabisReportsKey('dd95826f708d06482307116ea85706f52e95f7e6');

export default class List extends Component {

  render() {
    return (
        Strain
            .all()
            .then(data => <Text>{data}</Text>)
            .catch(err => console.log(err))
    );
  }
}
```
but it does not seem to be working. I am also using Shoutem for mobile development. I reached out to them and said they see this in their logs:
```
Unable to resolve module `url` from `/node_modules/cannabis-reports/lib/redirects.js`: Module does not exist in the module map or in these directories:
/node_modules
```

Also, when I try to run using https://npm.runkit.com/cannabis-reports I get `ReferenceError: Strain is not defined`.

**Comment by AJFunk** [comment]
I have not tested this with React Native unfortunately. The `url` module is a a built-in module that ships with Node. If you are not running this on Node, it won't be available to you. Instead of adding this library to React native, you can setup a Node server with this library, make your requests from React Native to your server, and then leverage this library there.

In regards to the Runkit error, this is because the use `require` instead of `import`. This imports the whole library as a single object, so you need to call `cannabisReports.Strain`
